// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0WXsSX8EbwmHNbyjL6R2x20aVqkGHJAQ',
    appId: '1:205403297790:web:af86123c8ea4095a5112af',
    messagingSenderId: '205403297790',
    projectId: 'rentrig-project',
    authDomain: 'rentrig-project.firebaseapp.com',
    storageBucket: 'rentrig-project.firebasestorage.app',
    measurementId: 'G-0KZXYGY901',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzd_724Sco4InpZ05AiiGZSx94ek231Hg',
    appId: '1:205403297790:android:1db0c9053a36f5825112af',
    messagingSenderId: '205403297790',
    projectId: 'rentrig-project',
    storageBucket: 'rentrig-project.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzEw7ehdoRwp0fbE-LYkMoMtgZakkFPoQ',
    appId: '1:205403297790:ios:2fbd1651696b60755112af',
    messagingSenderId: '205403297790',
    projectId: 'rentrig-project',
    storageBucket: 'rentrig-project.firebasestorage.app',
    iosBundleId: 'com.rentrig.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzEw7ehdoRwp0fbE-LYkMoMtgZakkFPoQ',
    appId: '1:205403297790:ios:2fbd1651696b60755112af',
    messagingSenderId: '205403297790',
    projectId: 'rentrig-project',
    storageBucket: 'rentrig-project.firebasestorage.app',
    iosBundleId: 'com.rentrig.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0WXsSX8EbwmHNbyjL6R2x20aVqkGHJAQ',
    appId: '1:205403297790:web:e274982aefac50e35112af',
    messagingSenderId: '205403297790',
    projectId: 'rentrig-project',
    authDomain: 'rentrig-project.firebaseapp.com',
    storageBucket: 'rentrig-project.firebasestorage.app',
    measurementId: 'G-CCHLGSM11E',
  );
}
